# Generated by Django 4.1.3 on 2022-12-10 18:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(help_text='فایل هایی که میخواهید در پست وبلاگ قرار دهید را در اینجا اپلود کنید', upload_to='files', verbose_name='فایل')),
                ('url', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل های وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/blog', verbose_name='تصویر')),
                ('url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته بندی های پست های وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblog_tag', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('writer', models.CharField(max_length=300, verbose_name='نویسنده')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='./images/blog/thumbnails')),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('category', models.ForeignKey(default='عمومی', on_delete=django.db.models.deletion.SET_DEFAULT, to='weblog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست های وبلاگ',
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['content_type', 'object_id'], name='weblog_tag_content_e94543_idx'),
        ),
    ]
